mutation CreateUser @auth(level: USER) {
  user_insert(data: {
    username_expr: "auth.uid",
    email: "example@example.com",
    passwordHash: "examplehash",
    createdAt_expr: "request.time"
  })
}

query ListServices @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  services {
    id
    name
    description
    pricePerUnit
  }
}

mutation UpdateOrderStatus($orderId: UUID!, $status: String!) @auth(level: USER) {
  order_update(
    id: $orderId,
    data: {
      status: $status
    }
  )
}

query GetUserTransactions @auth(level: USER) {
  transactions(where: {userId_expr: "auth.uid"}) {
    id
    amount
    createdAt
    type
    status
  }
}